fix vector unit test script

diff --git a/tests/riscv/riscv-vector-tests/run-test.sh.in b/tests/riscv/riscv-vector-tests/run-test.sh.in
--- a/tests/riscv/riscv-vector-tests/run-test.sh.in
+++ b/tests/riscv/riscv-vector-tests/run-test.sh.in
@@ -87,14 +87,20 @@ for testcase in "${testcases[@]}"; do
     filename=$(basename "$f")
     "$RISCV_TOOLCHAIN_PATH/bin/riscv$XLEN-unknown-elf-objdump" -D "$f" > "$filename.dump"
     "$RISCV_TOOLCHAIN_PATH/bin/riscv$XLEN-unknown-elf-objcopy" -O binary "$f" "$filename.bin"
+
+    set +e  # Temporarily disable exit on error
     "$SCRIPT_DIR/../../../sim/simx/simx" -v "$filename.bin" > "$filename.log"
-    if [ $? -eq 0 ]; then
+    sim_result=$? # Capture Simx exit status
+    set -e  # Re-enable exit on error
+
+    if [ $sim_result -eq 0 ]; then
       echo "$filename PASSED"
       let "passed+=1"
     else
       echo "$filename FAILED"
       let "failed+=1"
     fi
+    
     # REG_TESTS=1 informs the script to delete the previous binary after each vector test to save disk space
     # Otherwise, the vector regression tests would run out of disk space eventually
     if [ "$REG_TESTS" -eq "1" ]; then
