bug fixes

diff --git a/tests/riscv/riscv-vector-tests/run-test.sh.in b/tests/riscv/riscv-vector-tests/run-test.sh.in
--- a/tests/riscv/riscv-vector-tests/run-test.sh.in
+++ b/tests/riscv/riscv-vector-tests/run-test.sh.in
@@ -1,13 +1,14 @@
 #!/bin/bash
-RISCV_TOOLCHAIN_PATH=${RISCV_TOOLCHAIN_PATH:-$TOOLDIR"/riscv"$XLEN"-gnu-toolchain"}
 
+XLEN=${XLEN:-"@XLEN@"}
+TOOLDIR=${TOOLDIR:-"@TOOLDIR@"}
+RISCV_TOOLCHAIN_PATH=${RISCV_TOOLCHAIN_PATH:-"$TOOLDIR/riscv$XLEN-gnu-toolchain"}
 SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
-RESTORE_PREV_DIR=$(pwd)
 
 VECTOR_TESTS_REPOSITORY=https://github.com/MichaelJSr/testcases/raw/main
 VECTOR_TESTS_BASE_NAME=vector-tests.tar.bz2
 
-vector_tests()
+download_tests()
 {
     parts=$(eval echo {a..l})
     for x in $parts
@@ -20,15 +21,14 @@ vector_tests()
 }
 
 # get selected testcases from command line or run default testcases
-if [ "$#" == "0" ];
-then
+if [ "$#" -eq 0 ]; then
   # write out test case name explicitely if there are collisions with other test names
   testcases=(vmv vslide vmerge vrgather \
-             vlm.v vsm.v \ 
+             vlm.v vsm.v \
              vle8 vle16 vle32 \
              vse8 vse16 vse32 \
              vlseg vlsseg vluxseg vloxseg \
-#            vsseg vssseg vsuxseg vsoxseg \ # fails for both XLEN 32 and 64
+            # vsseg vssseg vsuxseg vsoxseg \ # fails for both XLEN 32 and 64
              vlse8 vlse16 vlse32 \
              vsse8 vsse16 vsse32 \
              vloxei vluxei vsoxei vsuxei \
@@ -51,70 +51,70 @@ then
              vadc vmadc vsbc vmsbc \
              vsext vzext \
              vid)
-  if [ $XLEN -eq 32 ]; then
+  if [ "$XLEN" -eq 32 ]; then
     testcases+=(vset) # fails for XLEN 64? Which doesn't make sense, since vset is essential, and other tests work
-  elif [ $XLEN -eq 64 ]; then
+  elif [ "$XLEN" -eq 64 ]; then
     testcases+=(vle64 vse64 vlse64 vsse64 vfwcvt vfncvt \
-#               vfwadd vfwsub \ # vfwadd.wf and vfwsub.wf fail, but .wv .vf and .vv pass
+                # vfwadd vfwsub \ # vfwadd.wf and vfwsub.wf fail, but .wv .vf and .vv pass
                 vfwmul vfwred vfwmacc vfwnmacc vfwmsac vfwnmsac )
   fi
 else
   testcases="${@}"
 fi
 
-cd $SCRIPT_DIR
-
 # Fallback #1: If testcases directory exists, use the existing testcases
 if [ ! -d "$SCRIPT_DIR/testcases" ]; then
+  pushd $SCRIPT_DIR
   mkdir testcases
-  cd testcases
+  pushd testcases
   # Fallback #2: Generate testcases
   if [ -n "$GEN_TESTS" ] && [ $GEN_TESTS -eq 1 ]; then
     /bin/bash ../gen-test.sh
   # Fallback #3: Download testcases
   else
-    vector_tests
+    download_tests
   fi
+  popd
 fi
 
-cd $SCRIPT_DIR/testcases/v$VLEN"x"$XLEN
+pushd "$SCRIPT_DIR/testcases/v${VLEN}x$XLEN"
 
-rm *".ddr4.log"
+rm -f "*.ddr4.log" > /dev/null 2>&1
 for testcase in ${testcases[@]}; do
-  rm "$testcase"*.elf "$testcase"*.bin "$testcase"*.dump "$testcase"*.log
+  rm -f "$testcase*.bin" "$testcase*.dump" "$testcase*.log" > /dev/null 2>&1
 done
 
 passed=0
 failed=0
 selected=0
 
-# count all available testcases, exclude *.elf, *.bin, *.dump, *.log to prevent double counting
-all=$(($(ls | wc -l) - $(ls -d *.elf | wc -l) - $(ls -d *.bin | wc -l) - $(ls -d *.dump | wc -l) - $(ls -d *.log | wc -l)))
-
 for testcase in ${testcases[@]}; do
-  for f in "$testcase"* ; do 
-    ln -s "$f" "$f.elf";
-    "$RISCV_TOOLCHAIN_PATH"/bin/riscv"$XLEN"-unknown-elf-objdump -D "$f.elf" > "$f.dump";
-    "$RISCV_TOOLCHAIN_PATH"/bin/riscv"$XLEN"-unknown-elf-objcopy -O binary "$f.elf" "$f.bin";
-    $SCRIPT_DIR/../../../sim/simx/simx -v -c 1 "$f.bin" &> "$f.log";
-    if [ $? -eq 1 ]; then
+  echo "Testcase: $testcase"
+  find . -type f -name "${testcase}*" 2>/dev/null | while read -r f; do
+    "$RISCV_TOOLCHAIN_PATH/bin/riscv$XLEN-unknown-elf-objdump" -D "$f" > "$f.dump"
+    "$RISCV_TOOLCHAIN_PATH/bin/riscv$XLEN-unknown-elf-objcopy" -O binary "$f" "$f.bin"
+    echo "running $SCRIPT_DIR/../../../sim/simx/simx -v $f.bin"
+    "$SCRIPT_DIR/../../../sim/simx/simx" -v "$f.bin" > "$f.log"
+    if [ $? -eq 0 ]; then
       echo "$f PASSED"
-      let "passed++"
+      ((passed++))
     else
       echo "$f FAILED"
-      let "failed++"
+      ((failed++))
+      exit 1
     fi
     # REG_TESTS=1 informs the script to delete the previous binary after each vector test to save disk space
     # Otherwise, the vector regression tests would run out of disk space eventually
     if [ -n "$REG_TESTS" ] && [ $REG_TESTS -eq 1 ]; then
-      cat $f.log
-      rm $f.*
-      rm $f
+      cat "$f.log"
+      rm -f "$f..bin" "$f.dump" "$f.log" > /dev/null 2>&1
     fi
-    let "selected++"
+    ((selected++))
   done
 done
-cd $RESTORE_PREV_DIR
+
+popd
+
 echo "Passed $passed out of $selected selected vector tests."
-echo "Total available vector tests: $all"
+
 exit $failed
